#!/usr/bin/env sh

# This script simply watches for an updated kernel. If an update is found, it
# will then kick off a packer build of the related operating system.
#
# Requires: GNU Sed
#
# Tested on: Mac OS X ElCapitan
#
# Author: Justin Cook 

set -x
set -o errexit
set -o nounset

MROR="http://mirror.bytemark.co.uk/fedora/linux/updates/23/x86_64/k/"
PLAT="fedora23"
TFIL="/tmp/`basename $0`.$$"
CACH=~/Library/Caches/`basename $0`

function cleanup {
  rm -f $TFIL
}

trap cleanup INT TERM EXIT

declare BILD=false

# Only build if the last known exists and does not match the current latest.
function check_cache {
  if [ ! -d $CACH ]
  then
    mkdir $CACH
    printf $1 > ${CACH}/${PLAT}
  fi
  if [ -s ${CACH}/${PLAT} ]
  then
    if [ "`cat ${CACH}/${PLAT}`" != "$1" ]
    then
      BILD=true
      printf $1 > ${CACH}/${PLAT}
    fi
  else
    printf $1 > ${CACH}/${PLAT}
  fi
}

curl $MROR -o $TFIL
KRNS=(`cat $TFIL | gsed -nr 's|.*(kernel-[-.0-9]+\.fc23\.x86_64\.rpm).*|\1|pg' \
      | sort -rnt. -k2,3`)

check_cache ${KRNS[0]}

if [ "$BILD" = true ]
then
  cd ~/repo/packer/${PLAT}
  packer build -var "_version_=`date +%Y.%m.%d.%H%M`" template.json
  if [ $? -eq 0 ]
  then
    read -d '' MESS  <<- _EOF_
    I have released a @fedora 23 @vagrantup box with @virtualbox
    provider https://atlas.hashicorp.com/jhcook/boxes/fedora23/versions/`date +%Y.%m.%d.%H%M`
_EOF_
  fi
fi
