#!/usr/bin/env sh

# This script simply watches for an updated kernel. If an update is found, it
# will then kick off a packer build of the related operating system.
#
# Requires: GNU Sed, Ruby gem t
#
# Tested on: Mac OS X ElCapitan
#
# Author: Justin Cook 

set -x
set -o errexit
set -o nounset

# cron does not parse profile and runtime files, so look in personal dir
source ~/.bashrc

# User editable variables
MROR="http://mirror.bytemark.co.uk/centos/7/updates/x86_64/Packages/"
PLAT="centos7"
TFIL="/tmp/`basename $0`.$$"
CACH=~/Library/Caches/`basename $0`

# The cleanup function ran at the beginning and end of exectution
function cleanup {
  rm -fr ~/repo/packer/${PLAT}/output-virtualbox-iso
  rm -f ~/repo/packer/${PLAT}/${PLAT}-virtualbox.box
  rm -f $TFIL
}

trap cleanup INT TERM EXIT

# Builds will be false by default unless it specifically meets requirements
declare BILD=false

# Only build if the last known exists and does not match the current latest.
function check_cache {
  if [ -s ${CACH}/${PLAT} ]
  then
    if [ "`cat ${CACH}/${PLAT}`" != "$1" ]
    then
      BILD=true
    fi
  fi
}

function update_cache {
  if [ ! -d $CACH ]
  then
    mkdir $CACH
  fi
  printf $1 > ${CACH}/${PLAT}
}

cleanup

curl $MROR -o $TFIL
KRNS=(`cat $TFIL | gsed -nr 's|.*(kernel-[-.0-9]+\.el7\.x86_64\.rpm).*|\1|pg' \
      | sort -rnt. -k4,5`)

check_cache ${KRNS[0]}

if [ "$BILD" = true ]
then
  cd ~/repo/packer/${PLAT}
  VER="`printf ${KRNS[0]} | gsed -r 's|kernel-(.*)\.el7.*|\1|g' | tr '-' '.'`"
  packer build -var "_version_=$VER" template.json
  if [ $? -eq 0 ]
  then
    update_cache ${KRNS[0]}
    MESS="I have released an update to #centos 7 @vagrantup box"
    MESS="$MESS with @virtualbox provider"
    MURL="https://atlas.hashicorp.com/jhcook/boxes/${PLAT}/versions/$VER"
    t update "$MESS $MURL"
  fi
fi
